# app/models/conversation.py
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Any, Union
from datetime import datetime
import uuid


@dataclass
class Message:
    """Model for representing a message in a conversation."""
    
    role: str  # 'user' or 'assistant'
    content: str
    timestamp: datetime = field(default_factory=datetime.now)
    
    # For audio messages
    audio_file_path: Optional[str] = None
    transcription: Optional[str] = None
    
    # ID generated by the database
    id: Optional[int] = None
    conversation_id: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Converts the message to a dictionary."""
        data = asdict(self)
        data['timestamp'] = self.timestamp.isoformat()
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Message':
        """Creates a Message object from a dictionary."""
        # Create a copy to avoid modifying the original
        data_copy = data.copy()
        
        # Convert timestamp if necessary
        if 'timestamp' in data_copy and isinstance(data_copy['timestamp'], str):
            data_copy['timestamp'] = datetime.fromisoformat(data_copy['timestamp'])
            
        return cls(**data_copy)


@dataclass
class Conversation:
    """Model for representing a complete conversation."""
    
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    lead_id: Optional[str] = None
    messages: List[Message] = field(default_factory=list)
    
    # Metadata
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)
    ended_at: Optional[datetime] = None
    
    # Summary and analysis
    summary: Optional[str] = None
    lead_info_extracted: Dict[str, Any] = field(default_factory=dict)
    
    def add_message(self, role: str, content: str, 
                   audio_file_path: Optional[str] = None,
                   transcription: Optional[str] = None) -> None:
        """Adds a message to the conversation."""
        message = Message(
            role=role,
            content=content,
            audio_file_path=audio_file_path,
            transcription=transcription
        )
        self.messages.append(message)
        self.updated_at = datetime.now()
    
    def end_conversation(self) -> None:
        """Marks the conversation as finished."""
        self.ended_at = datetime.now()
    
    def to_dict(self) -> Dict[str, Any]:
        """Converts the conversation to a dictionary."""
        data = {
            'id': self.id,
            'lead_id': self.lead_id,
            'messages': [msg.to_dict() for msg in self.messages],
            'created_at': self.created_at.isoformat(),
            'updated_at': self.updated_at.isoformat(),
            'summary': self.summary,
            'lead_info_extracted': self.lead_info_extracted
        }
        
        if self.ended_at:
            data['ended_at'] = self.ended_at.isoformat()
            
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Conversation':
        """Creates a Conversation object from a dictionary."""
        # Convert timestamps
        if 'created_at' in data and isinstance(data['created_at'], str):
            data['created_at'] = datetime.fromisoformat(data['created_at'])
        if 'updated_at' in data and isinstance(data['updated_at'], str):
            data['updated_at'] = datetime.fromisoformat(data['updated_at'])
        if 'ended_at' in data and isinstance(data['ended_at'], str) and data['ended_at']:
            data['ended_at'] = datetime.fromisoformat(data['ended_at'])
        
        # Convert messages
        messages = []
        for msg_data in data.get('messages', []):
            messages.append(Message.from_dict(msg_data))
        
        # Create the conversation without messages and then add them
        conversation = cls(
            id=data.get('id'),
            lead_id=data.get('lead_id'),
            created_at=data.get('created_at'),
            updated_at=data.get('updated_at'),
            ended_at=data.get('ended_at'),
            summary=data.get('summary'),
            lead_info_extracted=data.get('lead_info_extracted', {})
        )
        
        conversation.messages = messages
        return conversation